---
# grog.package
package_list:
  - name: bash-completion
  - name: curl
  - name: htop
  - name: ncdu
  - name: net-tools
  - name: nmap
  - name: sudo
  - name: tmux
  - name: tree
  - name: wget
  - name: zfsutils-linux

# geerlingguy.ntp
ntp_timezone: "America/New_York"

# ironicbadger.bash-aliases (formerly ferrarimarco.bash-aliases)
bash_aliases:
  - { alias: "dtail", command: "docker logs -tf --tail='50' " }
  - { alias: "dstop", command: "docker stop `docker ps -aq`" }
  - { alias: "drm", command: "docker rm `docker ps -aq`" }
  - { alias: "dcp", command: "docker-compose -f ~/docker-compose.yml " }
  - { alias: "dprune", command: "docker image prune" }
  - { alias: "dprunesys", command: "docker system prune --all" }
  - { alias: "dtop", command: "docker run --name ctop  -it --rm -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop" }
  - { alias: "appdata", command: "cd /mnt/tank/appdata" }
  - { alias: "zspace", command: "zfs list -o space" }
  - { alias: "zsnap", command: "zfs list -t snapshot" }

# artis3n.tailscale
tailscale_up_skip: true

# ironicbadger.docker_compose_generator
main_uid: "1000"
main_gid: "{{ main_uid }}"
appdata_path: /mnt/zfs/appdata
global_env_vars:
  - "PUID={{ main_uid }}"
  - "PGID={{ main_gid }}"
  - "TZ={{ ntp_timezone }}"
  - DOCKER_MODS=ghcr.io/tailscale-dev/docker-mod:main
  - TAILSCALE_STATE_DIR=/var/lib/tailscale
  - TAILSCALE_SERVE_MODE=https
  - TAILSCALE_SERVE_PORT=5000
  - TAILSCALE_USE_SSH=0