---

# ironicbadger.docker_compose_generator
containers:
  - service_name: id-demo-leaddev-berlin
    active: true
    image: ghcr.io/tailscale-dev/demo-id-headers:leaddev-berlin
    volumes:
      - "{{ appdata_path }}/2023/leaddev-berlin:/var/lib/tailscale"
    environment:
      - "TAILSCALE_AUTHKEY={{ tsauthkey_id_demo_test }}"
      - TAILSCALE_HOSTNAME=berlin23
      - TAILSCALE_FUNNEL=on
    include_global_env_vars: true
    restart: unless-stopped