---

# ironicbadger.docker_compose_generator
appdata_path: /mnt/zfs/appdata
containers:
  ########################
  ## Copy this block and modify for each additional demo required
  ########################
  ## Lead Dev Berlin - Dec 2023
  - service_name: id-demo-leaddev-berlin
    active: true
    image: ghcr.io/tailscale-dev/demo-id-headers:leaddev-berlin
    volumes:
      - "{{ appdata_path }}/2023/leaddev-berlin:/var/lib/tailscale"
    environment:
      - "TAILSCALE_AUTHKEY={{ tsauthkey_devrel }}"
      - TAILSCALE_HOSTNAME=berlin2023
      - TAILSCALE_FUNNEL=on
      - "DEMO_INVITE_LINK={{ leaddev_berlin_invite_link }}"
    include_global_env_vars: true
    restart: unless-stopped